
server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: APPLICATION
          uri: lb://APPLICATION
          predicates:
            - Path=/banking/**
        - id: micro
          uri: lb://micro
          predicates:
            - Path=/user/**
        - id: jwt
          uri: lb://jwt
          predicates:
            - Path=/token

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
    enabled: true
  instance:
    hostname: localhost

